mul = /* 0 *//* mul */ /* 0 */function (v1) { return /* free: ["v1"] */function (v2) { return /* free: ["v1","v2"] */v1 * v2; }; }
fix = /* 0 *//* fix */ /* 0 */function (v1) { return /* free: ["v1"] */fix = arguments.callee, v1(function (i) { return fix(v1)(i) }); }
list = /* 0 *//* list */ /* 0 */function (v3) { return /* free: ["v3"] */function (v4) { return /* free: ["v3","v4"] */function (v5) { return /* free: ["v3","v4","v5"] */v5.nil ? v3 : v4(v5.head)(v5.tail); }; }; }
add = /* 0 *//* add */ /* 0 */function (v5) { return /* free: ["v5"] */function (v6) { return /* free: ["v5","v6"] */v5 + v6; }; }
fix = /* 0 *//* fix */ /* 0 */function (v1) { return /* free: ["v1"] */fix = arguments.callee, v1(function (i) { return fix(v1)(i) }); }
list = /* 0 *//* list */ /* 0 */function (v3) { return /* free: ["v3"] */function (v4) { return /* free: ["v3","v4"] */function (v5) { return /* free: ["v3","v4","v5"] */v5.nil ? v3 : v4(v5.head)(v5.tail); }; }; }
fix = /* 0 *//* fix */ /* 0 */function (v3) { return /* free: ["v3"] */fix = arguments.callee, v3(function (i) { return fix(v3)(i) }); }
bool = /* 0 *//* bool */ /* 0 */function (v5) { return /* free: ["v5"] */function (v6) { return /* free: ["v5","v6"] */function (v7) { return /* free: ["v5","v6","v7"] */v7 ? v5(/*force*/) : v6(/*force*/); }; }; }
cons = /* 0 *//* cons */ /* 0 */function (v6) { return /* free: ["v6"] */function (v7) { return /* free: ["v6","v7"] */{ head : v6, tail : v7 }; }; }
sub = /* 0 *//* sub */ /* 0 */function (v6) { return /* free: ["v6"] */function (v7) { return /* free: ["v6","v7"] */v6 - v7; }; }
eq = /* 0 *//* eq */ /* 0 */function (v5) { return /* free: ["v5"] */function (v6) { return /* free: ["v5","v6"] */v5 == v6; }; }
cons = /* 0 *//* cons */ /* 0 */function (v5) { return /* free: ["v5"] */function (v6) { return /* free: ["v5","v6"] */{ head : v5, tail : v6 }; }; }
fix = /* 0 *//* fix */ /* 0 */function (v1) { return /* free: ["v1"] */fix = arguments.callee, v1(function (i) { return fix(v1)(i) }); }
bool = /* 0 *//* bool */ /* 0 */function (v3) { return /* free: ["v3"] */function (v4) { return /* free: ["v3","v4"] */function (v5) { return /* free: ["v3","v4","v5"] */v5 ? v3(/*force*/) : v4(/*force*/); }; }; }
cons = /* 0 *//* cons */ /* 0 */function (v4) { return /* free: ["v4"] */function (v5) { return /* free: ["v4","v5"] */{ head : v4, tail : v5 }; }; }
sub = /* 0 *//* sub */ /* 0 */function (v4) { return /* free: ["v4"] */function (v5) { return /* free: ["v4","v5"] */v4 - v5; }; }
eq = /* 0 *//* eq */ /* 0 */function (v3) { return /* free: ["v3"] */function (v4) { return /* free: ["v3","v4"] */v3 == v4; }; }
maybe = /* 0 *//* maybe */ /* 0 */function (v1) { return /* free: ["v1"] */function (v2) { return /* free: ["v1","v2"] */function (v3) { return /* free: ["v1","v2","v3"] */v3.nothing ? v1 : v2(v3.just); }; }; }
mul = /* 0 *//* mul */ /* 0 */function (v2) { return /* free: ["v2"] */function (v3) { return /* free: ["v2","v3"] */v2 * v3; }; }
just = /* 0 *//* just */ /* 0 */function (v1) { return /* free: ["v1"] */{ just : v1 }; }
sub = /* 0 *//* sub */ /* 0 */function (v1) { return /* free: ["v1"] */function (v2) { return /* free: ["v1","v2"] */v1 - v2; }; }
__main = /* 0 *//* 0 *//* 0 */mul(/* 0 *//* 0 *//* 0 */fix(/* 0 */function (v1) { return /* free: ["v1"] */function (v2) { return /* free: ["v1","v2"] *//* free: ["v1"] *//* 0 *//* 0 */list(/* 0 */0)(/* free: ["v1"] */function (v3) { return /* free: ["v1","v3"] */function (v4) { return /* free: ["v1","v3","v4"] *//* free: ["v3"] *//* 0 */add(/* free: ["v3"] */v3)(/* free: ["v1","v4"] *//* free: ["v1"] */v1(/* free: ["v4"] */v4)); }; })(/* free: ["v2"] */v2); }; })(/* 0 *//* 0 *//* 0 */fix(/* 0 */function (v1) { return /* free: ["v1"] */function (v2) { return /* free: ["v1","v2"] *//* free: ["v1"] *//* 0 *//* 0 */list(/* 0 *//* 0 *//* 0 */fix(/* 0 */function (v3) { return /* free: ["v3"] */function (v4) { return /* free: ["v3","v4"] *//* free: ["v3","v4"] *//* 0 *//* 0 */bool(/* 0 */function (v5) { return /* free: ["v5"] *//* 0 *//* 0 */function (v6) { return /* free: ["v6"] */function (v7) { return /* free: ["v6"] */v6; }; }(/* 0 */{ nil : 1 })(/* free: ["v5"] */v5); })(/* free: ["v3","v4"] */function (v5) { return /* free: ["v3","v4","v5"] *//* free: ["v3","v4"] *//* 0 */function (v6) { return /* free: ["v6"] */function (v7) { return /* free: ["v6"] */v6; }; }(/* free: ["v3","v4"] *//* 0 *//* 0 */cons(/* 0 */8)(/* free: ["v3","v4"] *//* free: ["v3"] */v3(/* free: ["v4"] *//* free: ["v4"] *//* 0 */sub(/* free: ["v4"] */v4)(/* 0 */1))))(/* free: ["v5"] */v5); })(/* free: ["v4"] *//* free: ["v4"] *//* 0 */eq(/* free: ["v4"] */v4)(/* 0 */0)); }; })(/* 0 */3))(/* free: ["v1"] */function (v3) { return /* free: ["v1","v3"] */function (v4) { return /* free: ["v1","v3","v4"] *//* free: ["v3"] *//* 0 */cons(/* free: ["v3"] */v3)(/* free: ["v1","v4"] *//* free: ["v1"] */v1(/* free: ["v4"] */v4)); }; })(/* free: ["v2"] */v2); }; })(/* 0 *//* 0 *//* 0 */fix(/* 0 */function (v1) { return /* free: ["v1"] */function (v2) { return /* free: ["v1","v2"] *//* free: ["v1","v2"] *//* 0 *//* 0 */bool(/* 0 */function (v3) { return /* free: ["v3"] *//* 0 *//* 0 */function (v4) { return /* free: ["v4"] */function (v5) { return /* free: ["v4"] */v4; }; }(/* 0 */{ nil : 1 })(/* free: ["v3"] */v3); })(/* free: ["v1","v2"] */function (v3) { return /* free: ["v1","v2","v3"] *//* free: ["v1","v2"] *//* 0 */function (v4) { return /* free: ["v4"] */function (v5) { return /* free: ["v4"] */v4; }; }(/* free: ["v1","v2"] *//* 0 *//* 0 */cons(/* 0 */8)(/* free: ["v1","v2"] *//* free: ["v1"] */v1(/* free: ["v2"] *//* free: ["v2"] *//* 0 */sub(/* free: ["v2"] */v2)(/* 0 */1))))(/* free: ["v3"] */v3); })(/* free: ["v2"] *//* free: ["v2"] *//* 0 */eq(/* free: ["v2"] */v2)(/* 0 */0)); }; })(/* 0 */3))))(/* 0 *//* 0 *//* 0 *//* 0 */maybe(/* 0 */4)(/* 0 */function (v1) { return /* free: ["v1"] *//* free: ["v1"] *//* 0 */mul(/* free: ["v1"] */v1)(/* 0 */8); })(/* 0 *//* 0 */just(/* 0 *//* 0 *//* 0 */sub(/* 0 */3)(/* 0 */2))))